###
POST http://localhost:3000/auth
Content-Type: application/json

{
  "username": "testuser1",
  "password": "password123"
}

> {% client.global.set("auth_token", response.body.token); %}

###
GET http://localhost:3000/users/
Authorization: Bearer {{auth_token}}

###
GET http://localhost:3000/users/10/5
Authorization: Bearer {{auth_token}}

###
GET http://localhost:3000/users/10001
Authorization: Bearer {{auth_token}}

###
GET http://localhost:3000/users/testuser1
Authorization: Bearer {{auth_token}}

###
GET http://localhost:3000/messages/2
Authorization: Bearer {{auth_token}}


###
POST http://localhost:3000/messages/post
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "senderId": 10040,
  "recipientId": 10031,
  "subject": "Lorem ipsum",
  "body": "Lorem ipsum dolor sit amet",
  "senderAddress": "123.123.123.123"
}

###
POST http://localhost:3000/messages/read
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 11,
  "readerAddress": "10.11.12.13"
}

###
POST http://localhost:3000/messages/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 4,
  "deletedBy": 10076
}

###
POST http://localhost:3000/users/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "99",
  "userUpdate": {
    "lastName": "User",
    "email": "email.address.@email.com",
    "deviceAddress": "74.45.45.99"
  }
}